# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VPSfW3b39jxwaf4fHMUDQgFl47xp8M9
"""

import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="Retail Business Performance Analysis",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Retail Business Performance Analysis")
st.caption("Interactive Power BI Dashboard")

st.markdown("""
### Business Objective

Evaluate business performance across products, customers, and markets by analyzing sales, profitability, customer segments, and regional trends. The analysis aims to uncover growth opportunities, improve profitability, and support strategic business decisions through interactive dashboards.

**Tools:** Python • Power BI

**Techniques:** Data Cleaning • Exploratory Data Analysis (EDA) • KPI Analysis • Customer Segmentation • K-Means Clustering
""")

st.divider()

components.iframe(
    "https://app.powerbi.com/view?r=eyJrIjoiODdhNzA5ZWEtNTk2NC00MzNmLWJiMzEtMjlhZTRiZTEzMjhiIiwidCI6IjgyMTE5NTA1LTdmNTYtNGUxZC04NTlhLWJiZWFjODNhNzhhMCIsImMiOjEwfQ%3D%3D",
    width=1400,
    height=850,
    scrolling=True
)